### ISSUE TITLE
PROJECT_DIR is read-only from inside container

### ISSUE THREAD

**Issue by tonzgao** [distributed-containers-inc/sanic#14]
root@migrator-d594c498c-d8x9h:/alembic# touch test
touch: cannot touch 'test': Read-only file system
root@migrator-d594c498c-d8x9h:/alembic# 

is this intentional?

my use case is I have a pod migrator which
1. runs alembic upgrade head on deploys
2. you can sanic enter to run alembic revision with access to the postgres pod

if it's read only, then the second point wont work

**Comment by ColinChartier** [comment]
Is this with the localdev provisioner?

The problem with creating files from pods is that they have restrictive permissions & are owned by root,  the read-only-ness comes from this file:

https://github.com/distributed-containers-inc/sanic/blob/master/pkg/provisioners/localdev/livemount.go

**Comment by tonygjerry** [comment]
ok, i can probably use a local persistent volume instead for this sort of thing

**Comment by tonzgao** [comment]
ok, i can probably use a local pv volume instead for this sort of thing
