### ISSUE TITLE
error running sanic

### ISSUE THREAD

**Issue by davidneudorfer** [distributed-containers-inc/sanic#4]
Steps to reproduce:
1. download sanic
2. moving it to `/usr/local/bin/sanic`
3. make it exec `chmod +x /usr/local/bin/sanic`
4. try running it

```
sanic
zsh: exec format error: sanic

sanic --help
zsh: exec format error: sanic

bash

bash-3.2$ sanic
bash: /usr/local/bin/sanic: cannot execute binary file

bash-3.2$ sanic --help
bash: /usr/local/bin/sanic: cannot execute binary file
```

to resolve:
```
rm /usr/local/bin/sanic
go get github.com/distributed-containers-inc/sanic
```

**Comment by ColinChartier** [comment]
What OS / instruction set are you using?

Could you try v1.2.2 from here: https://github.com/distributed-containers-inc/sanic/releases/tag/v1.2.2
