### ISSUE TITLE
only bash is supported when running bash

### ISSUE THREAD

**Issue by davidneudorfer** [distributed-containers-inc/sanic#5]
unable to run sanic
sanic version 1.0.0

**running zsh**
```
$ sanic env dev
only bash is supported

$ ps -o comm= $$
-zsh
```

**switch to bash**
```
$ bash

$ sanic env dev
only bash is supported

$ ps -o comm= $$
bash
```

**Comment by ColinChartier** [comment]
Ah, interesting -- It looks at your login shell right now.

I'll make it use $SHELL instead.

**Comment by ColinChartier** [comment]
Try now, I think this should be resolved now.

**Comment by leviable** [comment]
What I am seeing now:
```
bash-3.2$ sanic env dev
Warning: Bash is not your current shell, but it will be in a sanic environment.
bash needs to be installed to use sanic: exec: "fortune": executable file not found in $PATH
bash-3.2$ ps -o comm= $$
```

**Comment by ColinChartier** [comment]
Alright, I made one last revision. You can download or "go get" to resolve it.

https://github.com/distributed-containers-inc/sanic/releases/tag/v1.2.4
