### ISSUE TITLE
Version output is incorrect

### ISSUE THREAD

**Issue by dbirks** [distributed-containers-inc/sanic#6]
Hello, I'm building 1.2.6 from the release tarball, and it's reporting that it's at version 1.0.0. 

```
$ sanic -v
sanic version 1.0.0
```

I believe due to `app.Version` here:
https://github.com/distributed-containers-inc/sanic/blob/master/main.go#L25

Thanks for all your work on this!

**Comment by ColinChartier** [comment]
Should be resolved: https://github.com/distributed-containers-inc/sanic/commit/5669332222e3ab887c8c5dd3dd054bb4e03abf7d

I'll start bumping version numbers at tag time, but for now the tag 1.2.6 doesn't align with the commit that changes the version number.

**Comment by dbirks** [comment]
While updating the AUR package today, I noticed tag 1.2.11 had version 1.2.8 :P

I'm not a Go programmer, but I've seen other ways that look convenient, so it's not such a manual process. Kail puts [version in a var](https://github.com/boz/kail/blob/master/cmd/kail/main.go#L27), then it looks like it can be compiled [with a ldflag](https://github.com/boz/kail/blob/master/Makefile#L11) `-X main.version=1.2.11`. Oh and [with a small Makefile](https://github.com/boz/kail/blob/master/Makefile#L18) to do your bidding, it makes it easier to [grab the tag from git](https://github.com/Masterminds/glide/blob/master/Makefile#L3). (With maybe something like `git describe --abbrev=0 --tags`?)

Anyways, :man_cartwheeling: no worries :man_cartwheeling:  if you'd rather not. Just wanted to share what I've seen.

**Comment by ColinChartier** [comment]
I'm working on setting up CI to deal with versions automatically, hopefully this will be permanently resolved then.

**Comment by ColinChartier** [comment]
Thanks for the comprehensive comment, I've updated the build process to use that exact approach.

In your AUR package, add `--ldflags "-X main.version=$(git describe --abbrev=0 --tags)"` to the build line.

**Comment by dbirks** [comment]
Very cool :+1: 
Just updated the AUR package too.
